
server:
  port: 8090
  servlet:
    context-path: /vince-oauth2-sso
    
spring:
    h2:
      console:
        enabled: true
        path: /h2-console
    datasource:
      url: jdbc:h2:./data/demo
      username: sa  
      password: password     