
server:
  port: 8091
  servlet:
    context-path: /vince-multi-app
    
spring:
    h2:
      console:
        enabled: true
        path: /h2-console
    datasource:
      url: jdbc:h2:./data/demo
      username: sa  
      password: password  
      
    freemarker:
      template-loader-path: classpath:/templates
      suffix: .ftl               